DELETE http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Huong",
    "number": "123456"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "",
    "number": "13579"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "13579"
}
